# Generated by Django 4.0.7 on 2022-12-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=23)),
                ('age', models.CharField(max_length=5)),
                ('children', models.CharField(max_length=3)),
                ('rural', models.CharField(max_length=3)),
                ('executive', models.CharField(max_length=3)),
                ('employees', models.CharField(max_length=6)),
                ('wfh_days', models.IntegerField()),
                ('more_breaks', models.CharField(max_length=3)),
                ('wfh_day_condition', models.CharField(max_length=23)),
                ('productivity', models.CharField(max_length=25)),
            ],
        ),
    ]
